### ISSUE TITLE
Add diff type for typescript

### ISSUE THREAD

**Issue by sanex3339** [niieani/typescript-vs-flowtype#18]
Now we can add `diff` type to the TS section
```ts
type Diff<T extends string, U extends string> = ({[P in T]: P } & {[P in U]: never } & { [x: string]: never })[T];  
```

**Comment by niieani** [comment]
Can you link to the source of this? Thanks.
Also, PR's are welcome.

**Comment by sanex3339** [comment]
http://ideasintosoftware.com/typescript-advanced-tricks/

**Comment by pelotom** [comment]
It's not quite the same since `Diff` subtracts unions of literals, whereas `$Diff` subtracts objects. `Omit`, based on `Diff`, is closer:

```ts
type Omit<T, K extends keyof T> = {[P in Diff<keyof T, K>]: T[P]};

Omit<{ a: string, b: number }, 'a'> // = { b: number }
```

**Comment by n9** [comment]
https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-311923766

**Comment by niieani** [comment]
I'd appreciate a PR to the README. As long as there are no caveats with Omit (I remember initially there used to be), we can add it.

**Comment by niieani** [comment]
TS 2.8 now has official support. I'll close this issue and make an umbrella issue for 2.8.
