### ISSUE TITLE
type spread operator

### ISSUE THREAD

**Issue by vkurchatkin** [niieani/typescript-vs-flowtype#2]
Could you clarify, what you mean by `type spread operator`?

**Comment by niieani** [comment]
> The spread type `{ ...A, ...B }` combines the properties, but not the call or construct signatures, of entities A and B.

Source: https://github.com/Microsoft/TypeScript/pull/11150

**Comment by vkurchatkin** [comment]
Doesn't seems to work in repl

**Comment by niieani** [comment]
Ah, I think this still hasn't been released and is slated for TS 2.2. I'll add a note. Thanks for spotting.
