### ISSUE TITLE
More links

### ISSUE THREAD

**Issue by stereobooster** [niieani/typescript-vs-flowtype#28]
Hi. Thank you for this document, it is very helpful.

I want to share some links to the similar repos:
- [utility-types](https://github.com/piotrwitek/utility-types) - Utility Types for TypeScript (provide migration from Flow's Utility Types). Kind of similar project.
- [type-o-rama](https://github.com/stereobooster/type-o-rama) - JS type systems interportability
- https://github.com/tycho01/typical
- https://github.com/pelotom/type-zoo
- https://github.com/pelotom/hkts
- https://github.com/andnp/SimplyTyped

**Comment by niieani** [comment]
Hi @stereobooster, I'd be happy to accept a PR with a new section in the README with related links. 👍 
Thanks!
