### ISSUE TITLE
Remove "type-checking speed" sine it adds no value and might confuse people

### ISSUE THREAD

**Issue by mrkev** [niieani/typescript-vs-flowtype#30]
The notes themselves say it:

> (w/o transpilation, subjective, need benchmarks!)

Avik from the flow team mentioned its [speed degrades with the number of files added](https://www.youtube.com/watch?v=WgvAPzOmiP0&feature=youtu.be&t=616) about a year ago. These are all the facts.

1. This doesn't imply this is not the case with TypeScript (and in fact, it's not unlikely it is, given it's the most straightforward way to design a type-checker).
2. This doesn't imply it is still like this (the talk was from almost a year ago, and he mentioned they were looking to change this back then).
3. This gives no valuable information; if the speed of my software stays the same no matter how many files you throw at it, but that speed is a constant 5 days, yet there's other software that gets slower the more files you add, but it would need to be dealing with 50 billion files before taking 5 days to run, the time complexity at which the software runs is not enough to make an informed decision. This is an extreme example but **benchmarks are everything**.

Given there's no information whatsoever to compare the two, I do think it'd be better to delete this section to avoid misunderstanding and misguidance until someone builds a benchmark for both.

**Comment by niieani** [comment]
I agree, we need benchmarks.

I would keep the section, but simply remove the non-informative text, but keep the Flow section image, linking to a very in-depth talk about the speed of Flow. I think its good to keep, as it is still the way Flow works (it hasn't changed in the last year).

There is some anecdotal evidence that TypeScript is much faster, but I agree we should keep this repo as scientific as possible.

**Comment by mrkev** [comment]
Your'e right, it's a good analysis of flow's speed, it should be kept 👍

**Comment by niieani** [comment]
Closed by 61e4497.
