### ISSUE TITLE
Install Size comparison

### ISSUE THREAD

**Issue by styfle** [niieani/typescript-vs-flowtype#33]
I would like to add a row to compare the npm install size of TS vs Flow.

Would you like me to use the versions listed in the readme (TypeScript 2.6 and Flow 0.65) or use the latest versions?

|   | TypeScript            | Flow |
|---|------------------|--------|
|Install Size (old) | [![install size](https://packagephobia.now.sh/badge?p=typescript@2.6.2)](https://packagephobia.now.sh/result?p=typescript@2.6.2) | [![install size](https://packagephobia.now.sh/badge?p=flow-bin@0.65.0)](https://packagephobia.now.sh/result?p=flow-bin@0.65.0) |
| Install Size (latest) | [![install size](https://packagephobia.now.sh/badge?p=typescript)](https://packagephobia.now.sh/result?p=typescript) | [![install size](https://packagephobia.now.sh/badge?p=flow-bin)](https://packagephobia.now.sh/result?p=flow-bin) |

**Comment by niieani** [comment]
Sure, let's add it! Would be better to specify the versions instead of "old" though.

Thanks
