### ISSUE TITLE
Question: does Flow support dynamic import types

### ISSUE THREAD

**Issue by styfle** [niieani/typescript-vs-flowtype#53]
TypeScript 2.9 introduced a dynamic `import()` type feature. [View Blog Post](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#import-types)

Is there an equivalent in Flow?

**Comment by niieani** [comment]
There's an undocumented `$Exports<'module-name'>`, but I had issues with it in the past.

**Comment by styfle** [comment]
@niieani Should I add a row for this feature?

**Comment by niieani** [comment]
@styfle sure, that would be great! 👍
